### ISSUE TITLE
cmakeConsole template: update.json wants Makefile

### ISSUE THREAD

**Issue by Dualton** [toradex/vscode-torizon-templates#130]
When running task try-update-template, it fails with:

> Applying common tasks ...
> Copy-Item: /home/USER/git/PROJ/.conf/projectUpdater.ps1:219:5
> Line |
>  219 |      Copy-Item "$Env:HOME/.apollox/$templateName/$_source" .
>      |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Cannot find path '/home/USER/.apollox/cmakeConsole/Makefile' because it does not exist.

Line 219 tries to copy files mentioned in
[https://github.com/toradex/vscode-torizon-templates/blob/bookworm/cmakeConsole/.conf/update.json](url)

This file still references Makefile, even though a Makefile is not needed nor present.

**Comment by microhobby** [comment]
Hey @Dualton thanks for the report, this should be fixed when using the follow in the `settings.json`:

```json
"apollox.templatesBranch": "dev",
"apollox.templatesTag": "next",
```

Or in the next stable version.
