### ISSUE TITLE
Make a reference to the developer website docs on every template-specific doc

### ISSUE THREAD

**Issue by leograba** [toradex/vscode-torizon-templates#140]
The template-specific docs are automatically opened when a new project is created. It would be nice to let users know that, in addition to this, there is a complete doc on https://developer.toradex.com/torizon/application-development/ide-extension/

**Comment by leograba** [comment]
@andreriesco I am not sure https://github.com/toradex/vscode-torizon-templates/pull/139 actually fixes this. Can you check?

**Comment by andreriesco** [comment]
Hmm, actually it doesn't. I think the title is not aligned with the description

**Comment by leograba** [comment]
Updated, sorry for the confusion

**Comment by microhobby** [comment]
@andreriesco could you please handle this?

**Comment by andreriesco** [comment]
Sure

**Comment by andreriesco** [comment]
Fixed by [https://github.com/toradex/vscode-torizon-templates/commit/81e7a677bc1f9ea97a975685c2b31fa78dcb97ac](https://github.com/toradex/vscode-torizon-templates/commit/81e7a677bc1f9ea97a975685c2b31fa78dcb97ac)
