### ISSUE TITLE
Error with task try-update-template and try-update-template-accepting-all

### ISSUE THREAD

**Issue by rudhi31** [toradex/vscode-torizon-templates#173]
I get this error when I try the try-update-template task and also try-update-template-accepting-all task:
Get-Content: /home/rudhi/Toradex/IDE_projects/TestMonoProject/.conf/projectUpdater.ps1:69:17
Line |
  69 |  $templateName = Get-Content $projectFolder/.conf/.template
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path '/home/rudhi/Toradex/IDE_projects/TestMonoProject/.conf/.template' because it does not exist.

 *  The terminal process "pwsh '-nop', '/home/rudhi/Toradex/IDE_projects/TestMonoProject/.conf/projectUpdater.ps1', '/home/rudhi/Toradex/IDE_projects/TestMonoProject', 'TestMonoProject', '0'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
Apparently, a customer runs into the same issue as well: https://community.toradex.com/t/svg-icons-are-not-shown-in-display-pyside2/21606

I have VSCode version 1.85.2 and Torizon IDE version 2.4.0.

**Comment by microhobby** [comment]
Hey @rudhi31 thanks to report. You are using an outdated VS Code version. Could you please update it and try again? Let me know.

**Comment by rudhi31** [comment]
I just upgraded and I get the same error with version 1.86.0 as well.

**Comment by microhobby** [comment]
@rudhi31 after the project creation is kind of impossible to know which template was used if the file `.template` does not exist. So, please go to the `.conf` create a new text file called `.template`. The content of the file should be exactly the folder name used to create the project. You can see the folder names here: https://github.com/toradex/vscode-torizon-templates
This will solve an already-created project.

What I need to know from you is if, after the VS Code update, you could reproduce with a new project created.

**Comment by microhobby** [comment]
an R&D member team was able to reproduce this, and end up that the issue is from the VS Code Extension side, not in the templates side.
