### ISSUE TITLE
ASP.NET 8 Blazor Template `check-deps` wants dotnet-sdk-6.0 instead of dotnet-sdk-8.0

### ISSUE THREAD

**Issue by leograba** [toradex/vscode-torizon-templates#178]
I try to create a ASP.NET 8 Blazor project from template, using the IDE Extension version 2.4.1 (stable).

Here is the text output of `check-deps`:

```
Checking dependencies ...
👍 openssh-client installed
👍 sshpass installed
😵 dotnet-sdk-6.0 not installed
Do you want to try to install the dependencies? <y/N>: N
```

It ask for .NET 6 but it's a .NET 8 project.

Btw, I have .NET 8 installed from MS sources:

```
leonardo@leonardov-nb:~/projects/testASPDotNet8Blazor$ apt list --installed dotnet*
Listing... Done
dotnet-apphost-pack-8.0/jammy,now 8.0.2-1 amd64 [installed,automatic]
dotnet-host/jammy,now 8.0.2-1 amd64 [installed,automatic]
dotnet-hostfxr-8.0/jammy,now 8.0.2-1 amd64 [installed,automatic]
dotnet-runtime-8.0/jammy,now 8.0.2-1 amd64 [installed,automatic]
dotnet-runtime-deps-8.0/jammy,now 8.0.2-1 amd64 [installed,automatic]
dotnet-sdk-8.0/jammy,now 8.0.200-1 amd64 [installed]
dotnet-targeting-pack-8.0/jammy,now 8.0.2-1 amd64 [installed,automatic]
```

**Comment by leograba** [comment]
cc @andreriesco, since you are working on test and release of next patch, please consider also doing a stable patch release with this fix.

**Comment by andreriesco** [comment]
Fixed by [https://github.com/toradex/vscode-torizon-templates/commit/e3af56179adf6d2cf4225c55ddbdb48fe3c5a3d8](https://github.com/toradex/vscode-torizon-templates/commit/e3af56179adf6d2cf4225c55ddbdb48fe3c5a3d8)
