### ISSUE TITLE
GH Actions CI/CD excluded from Git when created from template

### ISSUE THREAD

**Issue by leograba** [toradex/vscode-torizon-templates#179]
I created a Qt 6 QML C++ project from template.

When following the article [CI/CD - Integrate With GitHub Actions](https://developer.toradex.com/torizon/application-development/ide-extension/github-actions), I was not able to trigger a GH Actions pipeline when pushing to the `main` branch.

I noticed the `.gitignore` file was excluding the `.github/workflows/build-application.yaml` file:

```
$ git add .github/workflows/build-application.yaml 
The following paths are ignored by one of your .gitignore files:
.github/workflows/build-application.yaml
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
```

Then confirmed it was the case patching the `.gitignore`:

```
diff --git a/.gitignore b/.gitignore
index c70dc10..fc6d1c6 100644
--- a/.gitignore
+++ b/.gitignore
@@ -11,6 +11,7 @@ credentials.zip
 *.lock.yml
 
 build-*
+!.github/workflows/build-*
 
 # After committing it once, to stop having modifications every time you do 
 # anything on Qt Creator (like dragging the window, literally almost anything),
```

After this, I added the missing file, pushed and got a CI triggered.

**Comment by microhobby** [comment]
thanks for the report and fix suggestion @leograba
