### ISSUE TITLE
GH Actions pipeline fails with error "❌ DOCKER_REGISTRY is not set"

### ISSUE THREAD

**Issue by leograba** [toradex/vscode-torizon-templates#180]
After setting up a Qt 6 QML C++ project from template, I followed [CI/CD - Configure Projects to Run CI Pipelines](https://developer.toradex.com/torizon/application-development/ide-extension/configure-ci-pipelines) and [CI/CD - Integrate With GitHub Actions](https://developer.toradex.com/torizon/application-development/ide-extension/github-actions).

Then, when the GH Actions pipeline is triggered, I get the following error:

```
> Executing task: validate-pipeline-settings <
❌ DOCKER_REGISTRY is not set
Missing settings.json properties, aborting


⚠️ THESE ENV VARIABLES NEED TO BE SET IN YOUR CI/CD ENVIRONMENT

Program "pwsh" ended with non-zero exit code: 69.

	at <ScriptBlock>, <No file>: line 1
	at runTask, /home/runner/work/WindowsTestQtCpp/WindowsTestQtCpp/.vscode/tasks.ps1: line 6[18](https://github.com/leograba/WindowsTestQtCpp/actions/runs/8160634036/job/22307627931#step:3:19)
	at taskArgumentExecute, /home/runner/work/WindowsTestQtCpp/WindowsTestQtCpp/.vscode/tasks.ps1: line 448
	at <ScriptBlock>, /home/runner/work/WindowsTestQtCpp/WindowsTestQtCpp/.vscode/tasks.ps1: line 672
	at <ScriptBlock>, /home/runner/work/_temp/e42f2ce0-8497-450f-a7a1-174c38f[28](https://github.com/leograba/WindowsTestQtCpp/actions/runs/8160634036/job/22307627931#step:3:29)e1c.ps1: line 9
	at <ScriptBlock>, <No file>: line 1

Error: Process completed with exit code 1.
```

Here is the job: https://github.com/leograba/WindowsTestQtCpp/actions/runs/8160634036/job/22307627931

Also, my `.vscode/settings.json` has the `docker_regsitry` (all in lower case) variable empty:

```
  "docker_registry": "",
```

**Comment by microhobby** [comment]
Fixed by #181
