### ISSUE TITLE
Dockerfile.sdk not being updated by the task try-update-template

### ISSUE THREAD

**Issue by andreriesco** [toradex/vscode-torizon-templates#187]
When running the `try-update-template` task on a project that has a `Dockerfile.sdk`, the `Dockerfile.sdk` is not being updated.

**Comment by andreriesco** [comment]
The same behavior is also applicable for `.vscode/settings.json` and `.vscode/launch.json`

**Comment by microhobby** [comment]
This was fixed on `next`
