### ISSUE TITLE
Bug when the disk space of the PC becomes zero

### ISSUE THREAD

**Issue by lucas-p-bernardes** [toradex/vscode-torizon-templates#191]
When the disk space of the PC becomes zero during "run-container-torizon-release-arm64", the files that extension were running were erased, that is the "Dockerfile" "Dockerfile.debug" and my "main.py".
Only the content of the file was erased, the file wasn't.

**Comment by microhobby** [comment]
Sorry @lucasbernardestoradex we are not able to reproduce this here. Please if this is 100% reproducible take a look at the VS Code side logs, this seems to be an issue there. If you think I'm wrong, feel free to reopen here.
