### ISSUE TITLE
Update the templates to use newer tcb (3.10.0)?

### ISSUE THREAD

**Issue by escherstair** [toradex/vscode-torizon-templates#197]
I see that some days ago TCB has been updated to release [3.10.0](https://github.com/toradex/torizoncore-builder/releases/tag/3.10.0).
I see that most of the templates are hardcoded to TCB 3.8.1 release.
Is it necessary to update the templates to use the newer release 3.10.0?

**Comment by microhobby** [comment]
hey @escherstair , no is not, you can change the version on your settings without update the template. Should work.

**Comment by escherstair** [comment]
> you can change the version on your settings

Do you mean changing `"tcb.version"` in `settings.json`?

**Comment by andreriesco** [comment]
Sure, it will also be updated in the 2.6 release, in [this commit](https://github.com/toradex/vscode-torizon-templates/commit/cd10ff0357bca2867b92a255dd5109ec479b5f82)
