### ISSUE TITLE
installDepsScripts for mono does not work

### ISSUE THREAD

**Issue by microhobby** [toradex/vscode-torizon-templates#198]
I'm getting the follow error:

```
The term './.conf/installDepsScripts/install-mono-devel.sh' is
     | not recognized as a name of a cmdlet, function, script file,
     | or executable program. Check the spelling of the name, or if a
     | path was included, verify that the path is correct and try
     | again.
```

**Comment by andreriesco** [comment]
Created a PR with the fix: [https://github.com/toradex/vscode-torizon-templates/pull/200]( https://github.com/toradex/vscode-torizon-templates/pull/200)

However, found a problem with other dependency that is being installed through apt
```
andreriesco@andreriesco-PC:~$ sudo apt install msbuild
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package msbuild
```

**Comment by microhobby** [comment]
this is only a dependency order issue. I think we should check first the script dependency and then the packages ones. The msbuild is only provided by the mono sources, and we are adding it before trying to get it from the debian one

**Comment by andreriesco** [comment]
Ok, updated the commit, now it is working
