### ISSUE TITLE
C++ CMake Console Application Template has no torizonPackages.json autocomplete feature

### ISSUE THREAD

**Issue by brunoaamello** [toradex/vscode-torizon-templates#205]
The [Ctrl+Space Autocomplete](https://developer.toradex.com/torizon/application-development/ide-extension/add-dependencies-and-tools-to-existing-project/#add-debian-packages-with-torizonpackagesjson) for packages on the `torizonPackages.json` file is not working for the ([C++ CMake Console Application](https://github.com/toradex/vscode-torizon-templates/tree/dev/cmakeConsole)) template.

When Ctrl+Space is pressed, it only gives suggestions for the local words in the file:

![Screenshot_20240524_100047](https://github.com/toradex/vscode-torizon-templates/assets/9855382/057b1587-e24c-43c4-9f2f-7e41b2bf72db)

The template also has the following warning for the `torizonPackages.json` file, which seems to be related to this problem:

```
Unable to load schema from 'debian://schemas/packages': cannot open debian://schemas/packages. Detail: Unable to resolve resource debian://schemas/packages.
```

**Comment by sunny52266** [comment]
I am affected by this issue as well. 

https://community.toradex.com/t/unable-to-resolve-packages-in-torizonpackages-json-in-a-c-cmake-project/24055/5
