### ISSUE TITLE
try-update-template fails after v2.5.0 update

### ISSUE THREAD

**Issue by escherstair** [toradex/vscode-torizon-templates#212]
I updated to v2.5.0 and I selected `try-update-template` for my python exampled created with v2.4.2.
This script failed with the following error
![immagine](https://github.com/toradex/vscode-torizon-templates/assets/22594460/a8d5a4c8-34d3-4fee-b53d-c8258ec0083a)

I had to create `.github\workflows` folder manually, before running `try-update-template`, and it worked.

**Comment by microhobby** [comment]
hey @escherstair , this is weird, so, there was not the `.github` folder before the update? Or was the `.github` folder deleted during the try update? We were unable to reproduce on our side.

**Comment by escherstair** [comment]
Hy @microhobby 
I've double checked.
I deleted the folder some weeks ago because I though "I don't need these files, since I use Azure DevOps, not github or gitlab".
My fault.
