### ISSUE TITLE
cppSlint not working

### ISSUE THREAD

**Issue by andreriesco** [toradex/vscode-torizon-templates#233]
cppSlint failing, with the following error:
```
autotests260arm64-1  | slint linuxkms backend: unrecognized renderer skia, falling back default
autotests260arm64-1  | Hello Torizon!
autotests260arm64-1  | Using Skia OpenGL renderer
autotests260arm64-1  | Rendering at 1920x1080
autotests260arm64-1  | thread '<unnamed>' panicked at api/cpp/lib.rs:64:6:
autotests260arm64-1  | called `Result::unwrap()` on an `Err` value: OtherError("Error presenting fb: permission denied")
autotests260arm64-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by tronical** [comment]
That would be a bug in the docker file. Maybe it changed since my PR. What version/branch are you using?

**Comment by tronical** [comment]
Sorry, I meant docker compose file

**Comment by tronical** [comment]
Also, are there any other processes running on the system that may claim the display by chance?

**Comment by andreriesco** [comment]
The [next branch](https://github.com/toradex/vscode-torizon-templates/tree/next). Also, this error happened on the release (Dockerfile).

**Comment by andreriesco** [comment]
Interestingly, I double checked it outside of the automated tests and it looks like it is working now:
```
Attaching to testslint-1
testslint-1  | slint linuxkms backend: unrecognized renderer skia, falling back default
testslint-1  | Hello Torizon!
testslint-1  | Using Skia OpenGL renderer
testslint-1  | Rendering at 1920x1080
```

**Comment by andreriesco** [comment]
Maybe it was just some bug on my display

**Comment by andreriesco** [comment]
Now it worked even on the automated tests :)

**Comment by tronical** [comment]
Yay :). Very much looking forward to the next release.
