### ISSUE TITLE
Rust Console Maintainance 

### ISSUE THREAD

**Issue by microhobby** [toradex/vscode-torizon-templates#272]
@skkywalker as maintainer of this template, would like to continue maintaining? 
The next update will bump major, with breaking changes, and we will clean the templates. Let us know.
https://github.com/torizon/vscode-torizon-templates/pull/268

**Comment by skkywalker** [comment]
Hi @microhobby, I won't have time to update it. If no one picks this up, it should be removed. Thanks for the ping
