### ISSUE TITLE
What is the maintenance and deprecation policy for the community templates?

### ISSUE THREAD

**Issue by leograba** [toradex/vscode-torizon-templates#31]
I've read https://github.com/toradex/vscode-torizon-templates/blob/main/CONTRIBUTING.md and didn't find a note on the maintenance policy for the templates.

With time, they may break so community contributors should be aware they are expected to update the templates, otherwise, we will end up with many non-working ones.

Also, we should have a deprecation policy for when a community template becomes unmaintained for any reason, for example, the original maintainer doesn't want to keep it anymore or ourselves.

It might be good to think of a badge to add on each template on https://github.com/toradex/vscode-torizon-templates#community-supported-templates, maybe with the "last updated" date, or something that can indicate to users the health of the community templates. Most users will not come to this GitHub repo, so this info should also be displayed in VS Code when creating a new project from a template.

**Comment by microhobby** [comment]
@leograba we added a section about it on the Contributing guidelines. Now we are working to add the badge on the VS Code UI side.

**Comment by microhobby** [comment]
@leograba the badge is getting the data from `templates.json` and it's already on the `pre-release` of the extension on VS Market Place.

**Comment by leograba** [comment]
Cool, thanks!
