### ISSUE TITLE
console-rust template doesn't build with production Dockerfile

### ISSUE THREAD

**Issue by tronical** [toradex/vscode-torizon-templates#53]
The copy instruction to deploy the target binary in rust-console's Dockerfile makes two incorrect assumptions:

` COPY --from=Build /app/debug /app`

1. That the production build is a debug build.
2. That the build was a "native" build based on the default target platform.

However the earlier build instructions run `cargo build --target XXX` and consequently the binaries end up in `target/XXX/debug`.

I think the production build should do a release build, and some trickery is needed to copy it out of the `target/XXX/release/` directory.

(I need that trickery anyway in the Slint template, so if I find a good solution I'll post it here)

**Comment by microhobby** [comment]
@skkywalker could you take a look?

**Comment by tronical** [comment]
I ended up using a bit of a hack: https://github.com/toradex/vscode-torizon-templates/blob/6fdf7437a9b627b805c4b5899f9ef71a3e192ded/rustSlint/Dockerfile#L72

**Comment by microhobby** [comment]
Solved by #64
