### ISSUE TITLE
Typo in Dockerfile.debug for nodeJSTypeScript sample

### ISSUE THREAD

**Issue by escherstair** [toradex/vscode-torizon-templates#63]
In file `Dockerfile.debug` for nodeJSTypeScript sample ther is the following typo that refers to .NET Uno templates
https://github.com/toradex/vscode-torizon-templates/blob/1256dec394eaf04ae675d1499fd04c2cc159c571/nodeJSTypeScript/Dockerfile.debug#L31

I suggest to change it either to
```
# Deploy Step
```
as done in cppConsole
or to
```
# Deploy Step Node.js Typescript
```

**Comment by microhobby** [comment]
It was fixed by 8f1483e41e875f23fe6f9c9d24064265efa785ca
