### ISSUE TITLE
Sharing a containerized application

### ISSUE THREAD

**Issue by Varmod** [toradex/vscode-torizon-templates#87]
Hi,

I'm trying to share a production prototype with my client but I'm having trouble due to the application being containerized and having very little experience with docker.

For context, the application is based on the [AvaloniaFrameBuffer](https://github.com/toradex/vscode-torizon-templates/tree/bookworm/dotnetAvaloniaFrameBuffer) template.

My idea was to save a docker image and send it alongside with the docker-compose.yml and built dotnet project. Possibly create a custom deploy script for them.

1. Copy over the docker-compose.yml and docker-image.tar to board
2. Load the image via 'docker load' 
3. Run 'docker compose up' to start the container
4. And finally copy over the built application into the container.
This happens all well but nothing happens afterwards. The container just sits blank. It's most likely waiting for a command to run the image but I can't figure out how to do it.

Thanks in advance

**Comment by Varmod** [comment]
Okay turns out all I had to do was start the app with something like:
docker exec -it container bash
cd /home/torizon/app 
./my-app

So maybe just a question if this whole approach is okay, or if there is easier way to do it?

**Comment by microhobby** [comment]
Hey @Varmod 

I think that you are exporting the debug image instead the production one. Because the production Dockerfile has the command to execute it already:
https://github.com/toradex/vscode-torizon-templates/blob/34e86493492453eb2559a1ff6adbed0cd979013b/dotnetAvaloniaFrameBuffer/Dockerfile#L102

**Comment by Varmod** [comment]
Hi, 

Thank you for the observation, the production image does indeed look like a better choice for my scenario. 

I had a go at it and noticed a few things. 
[Line 72](https://github.com/toradex/vscode-torizon-templates/blob/34e86493492453eb2559a1ff6adbed0cd979013b/dotnetAvaloniaFrameBuffer/Dockerfile#L72) wouldn't built for me as it is incomplete. Probably should be:
```
apt-get clean && apt-get autoremove && \
    rm -rf /var/lib/apt/lists/*
```
And at the end the
```
CMD [ "./app/__change__" ]
```
gave me errors when I ran my app as it couldn't find my app resources because it was looking in the wrong dir.
This seemed like a better choice for me:
```
cmd cd /app && ./__change__
```

**Comment by microhobby** [comment]
> gave me errors when I ran my app as it couldn't find my app resources because it was looking in the wrong dir.
> This seemed like a better choice for me:
> 
> ```
> cmd cd /app && ./__change__
> ```

hmm, this makes sense though. If you have the availability to contribute to this change, merge requests are welcome.

**Comment by microhobby** [comment]
@Varmod I think that the question here was answered, so, I will close this.
