### ISSUE TITLE
`rustSlint` production image does not build correctly

### ISSUE THREAD

**Issue by microhobby** [toradex/vscode-torizon-templates#95]
The `torizon/wayland-base` is set with a wrong base tag

**Comment by tronical** [comment]
Would it be possible to paste the error message here? I'm curious:)

I also wonder if there's an ways to build the production image locally without an automatic push to the registry.

**Comment by microhobby** [comment]
Hey @tronical don't worry I'll sign this issue for myself. This was introduced by 469bb576303814afb3ea66d5b8fad14ac4a33bfc and the root cause is that in the production `Dockerfile` we are not using the Slint base images, because we only use the already compiled binary, so base tag doesn't exist.

https://github.com/toradex/vscode-torizon-templates/blob/bookworm/rustSlint/Dockerfile#L69

I will fix this in the next few days.

**Comment by microhobby** [comment]
> I also wonder if there's an ways to build the production image locally without an automatic push to the registry.

There is no way, I will open a ticket to have it, thanks to point it.
