### ISSUE TITLE
Feature to run tasks to install dependencies that do not come from `dpkg`

### ISSUE THREAD

**Issue by microhobby** [toradex/vscode-torizon-templates#98]
In some cases, templates need to install dependencies that are not installable via `apt-get` or are not available from the default sources of supported distributions. So, we need some way to run the `check-deps` and also run these deps tasks.

**Comment by andreriesco** [comment]
Fixed by [https://github.com/toradex/vscode-torizon-templates/commit/e3af56179adf6d2cf4225c55ddbdb48fe3c5a3d8](https://github.com/toradex/vscode-torizon-templates/commit/e3af56179adf6d2cf4225c55ddbdb48fe3c5a3d8)
